#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : yajl
Version  : 2.1.0
Release  : 18
URL      : https://github.com/lloyd/yajl/archive/2.1.0.tar.gz
Source0  : https://github.com/lloyd/yajl/archive/2.1.0.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : MIT
Requires: yajl-bin
Requires: yajl-lib
BuildRequires : cmake
Patch1: 0001-change-test-location.patch

%description
**********************************************************************
This is YAJL 2.  For the legacy version of YAJL see
https://github.com/lloyd/yajl/tree/1.x
**********************************************************************

%package bin
Summary: bin components for the yajl package.
Group: Binaries

%description bin
bin components for the yajl package.


%package dev
Summary: dev components for the yajl package.
Group: Development
Requires: yajl-lib
Requires: yajl-bin

%description dev
dev components for the yajl package.


%package lib
Summary: lib components for the yajl package.
Group: Libraries

%description lib
lib components for the yajl package.


%prep
%setup -q -n yajl-2.1.0
%patch1 -p1

%build
mkdir clr-build
pushd clr-build
cmake .. -G "Unix Makefiles" -DCMAKE_INSTALL_PREFIX=/usr -DBUILD_SHARED_LIBS:BOOL=ON -DLIB_INSTALL_DIR:PATH=%{_libdir} -DLIB_SUFFIX=64
make V=1  %{?_smp_mflags}
popd

%check
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost
pushd test/parsing; ./run_tests.sh; cd ../api; ./run_tests.sh; popd

%install
rm -rf %{buildroot}
pushd clr-build
%make_install
popd

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/json_reformat
/usr/bin/json_verify

%files dev
%defattr(-,root,root,-)
/usr/include/yajl/yajl_common.h
/usr/include/yajl/yajl_gen.h
/usr/include/yajl/yajl_parse.h
/usr/include/yajl/yajl_tree.h
/usr/include/yajl/yajl_version.h
/usr/lib64/*.so
/usr/lib64/pkgconfig/*.pc

%files lib
%defattr(-,root,root,-)
/usr/lib64/*.so.*
